[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  port = 8888

# Proxy frontend calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
